#!/usr/bin/bash

# run at same time
sudo python3 controller.py & sudo python3 radioRover.py

# after successful run of first command, run second
# sudo python3 controller.py && sudo python3 radioRover.py